spring.application.name=energy-producer
app.queue.name=energy_queue
app.scheduling.fixed-delay-ms=1000

app.production.min-kwh=0.001
app.production.max-kwh=0.006
app.weather.latitude=48.2082
app.weather.longitude=16.3738

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
