spring.application.name=energy-user
app.queue.name=energy_queue
app.scheduling.fixed-delay-ms=1000
app.scheduling.max-random-delay-ms=4000

app.message.type=USER
app.message.association=COMMUNITY

app.usage.base-kwh=0.001
app.usage.variation-kwh=0.002
app.usage.peak-multiplier=3.0
app.usage.night-multiplier=0.5
app.usage.normal-multiplier=1.0


spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
