spring.application.name=usage-service
app.queue.name=energy_queue
app.update-queue.name=percentage_update_queue
app.message.producer-type=PRODUCER
app.message.user-type=USER
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_community
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
